Added binding simple view model with form
AKudlai/LearnKnockoutjs pull request #3
Opened 2019-11-17 20:41 UTC by AKudlai

2019-11-18 14:09 UTC, nbosy commented on LearnKnockoutjs/App_Start/RouteConfig.cs
> +    #region Usings
можно не выделять юзинги в регионы, если не ошибаюсь начиная с 15 студии юзинги автоматически уже группируются, раньше это делали для того, что бы можно было свернуть/развернуть все группы - сейчас юзинги автоматом сворачиваются/разворачиваются

2019-11-18 14:27 UTC, nbosy commented on LearnKnockoutjs/Scripts/app/employee.js
> +this.ko.applyBindings(new Employee());
Байндинг лучше всего делать в отдельной секции script на странице, где лежит форма, тем самым ты отделяешь логику скриптов от ее байндинга.

Пример:
<script>
var employee = new Employee();
ko.applyBindings(employee, '#form_id');
</script>

так же добавлю, что лучше использовать опциональный параметр для байндинга модели на определенную форму т.к. это работает быстрее, и будет меньше ошибок - если у тебя на странице несколько байндингов с одинаковыми моделями но относятся к разным моделям
https://knockoutjs.com/documentation/observables.html

> Optionally, you can pass a second parameter to define which part of the document you want to search for data-bind attributes. For example, ko.applyBindings(myViewModel, document.getElementById('someElementId')). This restricts the activation to the element with ID someElementId and its descendants, which is useful if you want to have multiple view models and associate each with a different region of the page.

2019-11-18 14:29 UTC, bosyi-mykola requested changes
исправь байндинг согласно замечаниям

2019-11-18 18:16 UTC, AKudlai commented on LearnKnockoutjs/Scripts/app/employee.js
> +this.ko.applyBindings(new Employee());
Мне казалось, что использовать секции script во View — плохой тон. Кроме того, бандлы cо скриптами подключаются в _Layout.cshtml перед </body> и уже после @RenderBody(). Т.е. ни employee.js, ни knockout.js еще нет во время обработки этой секции.

2019-11-18 18:17 UTC, AKudlai commented on LearnKnockoutjs/App_Start/RouteConfig.cs
> +    #region Usings
Согласен, как-то не обращал внимание. Удаляю.

2019-11-19 12:42 UTC, nbosy commented on LearnKnockoutjs/Scripts/app/employee.js
> +this.ko.applyBindings(new Employee());
закинь создание и байндинг в document ready
```
$(function() {
  // Handler for .ready() called.
});

или

$( document ).ready(function() {
  // Handler for .ready() called.
});
```

> Мне казалось, что использовать секции script во View
Нет, если на странице только создаются объекты и происходит инициализация каких-то элементов для этой страницы - это показывает что для данной страницы ты вызываешь создаешь и работаешь с объектом, инициализируешь его и т.п. (байндишь для определенной формы)

2019-11-19 12:49 UTC, nbosy commented on LearnKnockoutjs/Scripts/app/employee.js
> +ko.applyBindings(employee, document.getElementById('user-form-id'));
вот это не очень подходящее место для инициализации байндинга и создание объекта, лучше всего это делать на нужной странице
и.к. ты можешь подключить бандл с этим скриптом на разные страницы, у тебя всегда будет создаваться и байндиться объект, что не уместно для страниц на которых это не нужно

и лучше используй получение объекта с помощью jQuery вместо стандартного document.getElementBy...

2019-11-25 11:06 UTC, bosyi-mykola approved these changes

2019-11-26 11:38 UTC, merged